# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucumber-newrelic}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jesse Newland"]
  s.date = %q{2010-06-09}
  s.description = %q{Cucumber steps for verifing metrics from NewRelic's API}
  s.email = %q{jnewland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "config/newrelic.yml.example",
     "cucumber-newrelic.gemspec",
     "features/cucumber.feature",
     "features/steps/config_steps.rb",
     "features/support/env.rb",
     "lib/cucumber/newrelic.rb",
     "lib/cucumber/newrelic/steps.rb",
     "lib/cucumber/newrelic/version.rb"
  ]
  s.homepage = %q{http://github.com/jnewland/cucumber-newrelic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Cucumber steps for verifing metrics from NewRelic's API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<newrelic_rpm>, ["~> 2.10.6"])
      s.add_runtime_dependency(%q<activeresource>, ["~> 2.3.8"])
    else
      s.add_dependency(%q<newrelic_rpm>, ["~> 2.10.6"])
      s.add_dependency(%q<activeresource>, ["~> 2.3.8"])
    end
  else
    s.add_dependency(%q<newrelic_rpm>, ["~> 2.10.6"])
    s.add_dependency(%q<activeresource>, ["~> 2.3.8"])
  end
end

